import {IObjectData} from "./models";

export const temporaryData: IObjectData[] = [
    {
        "id": 9,
        "gender": "M",
        "first_name": "Уильям",
        "last_name": "Уэльский, принц",
        "maiden_name": null,
        "birth": "1982-06-21",
        "death": null,
        "birth_ca": null,
        "death_ca": null,
        "spouse": [
            11
        ],
        "father": 3,
        "mother": 7,
        "bio": "",
        "photo": null,
        "tree_owner": false,
        "no_parents": false,
    },

    {
        "id": 11,
        "gender": "F",
        "first_name": "Кэтрин",
        "last_name": "Уэльская, принцесса",
        "maiden_name": "Миддлтон",
        "birth": "1982-01-09",
        "death": null,
        "birth_ca": null,
        "death_ca": null,
        "spouse": [
            9
        ],
        "father": 27,
        "mother": null,
        "bio": "",
        "photo": null,
        "tree_owner": false,
        "no_parents": true,
    },

    {
        "id": 13,
        "gender": "M",
        "first_name": "Джордж",
        "last_name": "Кембриджский",
        "maiden_name": null,
        "birth": "2012-12-03",
        "death": null,
        "birth_ca": null,
        "death_ca": null,
        "spouse": [],
        "father": 9,
        "mother": 11,
        "bio": "",
        "photo": null,
        "tree_owner": true,
        "no_parents": false,
    },
    {
        "id": 7,
        "gender": "F",
        "first_name": "Диана",
        "last_name": "Уэльская, принцесса",
        "maiden_name": "Спенсер",
        "birth": "1961-07-01",
        "death": "1997-08-31",
        "birth_ca": null,
        "death_ca": null,
        "spouse": [
            3
        ],
        "father": null,
        "mother": null,
        "bio": "Diana, Princess of Wales",
        "photo": null,
        "tree_owner": false,
        "no_parents": true,
    },
    {
        "id": 3,
        "gender": "M",
        "first_name": "Карл III",
        "last_name": "Виндзор",
        "maiden_name": null,
        "birth": "1948-11-14",
        "death": null,
        "birth_ca": null,
        "death_ca": null,
        "spouse": [
            7,
            8
        ],
        "father": 2,
        "mother": 1,
        "bio": "Карл III[a][b] (англ. Charles III, произношение: /tʃɑːlz/), полное имя Чарльз Фили́пп Артур Джордж (англ. Charles Philip Arthur George; род. 14 ноября 1948, Букингемский дворец, Лондон) — царствующий король Великобритании и Северной Ирландии и королевств Содружества из Виндзорской династии, верховный главнокомандующий вооружёнными силами Великобритании, верховный правитель Церкви Англии, глава Содружества наций с 8 сентября 2022 года. Действующий монарх в четырнадцати независимых государствах: Австралии, Антигуа и Барбуде, Багамских Островах, Белизе, Гренаде, Канаде, Новой Зеландии, Папуа — Новой Гвинее, Сент-Винсенте и Гренадинах, Сент-Китсе и Невисе, Сент-Люсии, Соломоновых Островах, Тувалу и Ямайке.",
        "photo": null,
        "tree_owner": false,
        "no_parents": false,
    },
    {
        "id": 1,
        "gender": "F",
        "first_name": "Елизавета II",
        "last_name": "Виндзор",
        "maiden_name": null,
        "birth": "1926-04-21",
        "death": "2022-09-08",
        "birth_ca": null,
        "death_ca": null,
        "spouse": [
            2
        ],
        "father": null,
        "mother": null,
        "bio": "",
        "photo": null,
        "tree_owner": false,
        "no_parents": true
    },
    {
        "id": 2,
        "gender": "M",
        "first_name": "Филипп",
        "last_name": "Эдинбургский, герцог",
        "maiden_name": null,
        "birth": "1921-06-10",
        "death": "2021-04-09",
        "birth_ca": null,
        "death_ca": null,
        "spouse": [
            1
        ],
        "father": null,
        "mother": null,
        "bio": "",
        "photo": null,
        "tree_owner": false,
        "no_parents": true
    },
    {
        "id": 27,
        "gender": "M",
        "first_name": "Bla bla",
        "last_name": "Bla bla",
        "maiden_name": "Миддлтон",
        "birth": "1982-01-09",
        "death": null,
        "birth_ca": null,
        "death_ca": null,
        "spouse": [
            39
        ],
        "father": null,
        "mother": null,
        "bio": "",
        "photo": null,
        "tree_owner": false,
        "no_parents": true,
    },
]